//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project1.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Loan
    {
        [Required]
        public int LoanID { get; set; }
        [Required]
        public long AccountID { get; set; }
        [Required]
        public long LoanAmount { get; set; }
        [Required]
        public string LoanType { get; set; }
        [Required]
        public int Tenure { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
