//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan
    {
        public int LoanID { get; set; }
        public long AccountID { get; set; }
        public long LoanAmount { get; set; }
        public string LoanType { get; set; }
        public int Tenure { get; set; }
    
        public virtual Account Account { get; set; }
    }
}
