//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transcation
    {
        public int Id { get; set; }
        public Nullable<long> PayeeAccountNo { get; set; }
        public Nullable<long> BenificiaryAccNo { get; set; }
        public Nullable<long> ChequeNo { get; set; }
        public string PayeeName { get; set; }
        public Nullable<long> Amount { get; set; }
        public string BankName { get; set; }
        public string IFSC { get; set; }
    }
}
