//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Table1
    {
        public int Account_Number { get; set; }
        public string Account_Holdername { get; set; }
        public string Email { get; set; }
        public string Password { get; set; }
        public string Confirm_Password { get; set; }
        public Nullable<long> Mobile_No { get; set; }
        public string PAN { get; set; }
        public Nullable<long> Aadhaar { get; set; }
        public string Address { get; set; }
    }
}
